[supervisord]
nodaemon=true

[program:celery-batch_update]
command=celery -A src.tasks.batch.update.tasks worker --loglevel=info -Q batch_update --concurrency=10 --statedb=/app/worker-batch_update.state
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/app-batch_update.log
stdout_logfile=/app/app-batch_update.log

[program:celery-homelette]
command=celery -A src.tasks.homelette.tasks worker --loglevel=info -Q homelette --concurrency=10 --statedb=/app/worker-homelette.state
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/app-homelette.log
stdout_logfile=/app/app-homelette.log

[program:celery-musite]
command=celery -A src.tasks.musite.tasks worker --loglevel=info -Q musite --concurrency=10 --statedb=/app/worker-musite.state
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/app-musite.log
stdout_logfile=/app/app-musite.log

[program:celery-boltz]
command=celery -A src.tasks.boltz.tasks worker --loglevel=info -Q boltz --concurrency=10 --statedb=/app/worker-boltz.state
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/app-boltz.log
stdout_logfile=/app/app-boltz.log

[program:celery-diffab]
command=celery -A src.tasks.diffab.tasks worker --loglevel=info -Q diffab --concurrency=10 --statedb=/app/worker-diffab.state
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/app-diffab.log
stdout_logfile=/app/app-diffab.log

[program:celery-gnina]
command=celery -A src.tasks.gnina.tasks worker --loglevel=info -Q gnina --concurrency=10 --statedb=/app/worker-gnina.state
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/app-gnina.log
stdout_logfile=/app/app-gnina.log

[program:celery-gan]
command=celery -A src.tasks.gan.tasks worker --loglevel=info -Q gan --concurrency=10 --statedb=/app/worker-gan.state
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/app-gan.log
stdout_logfile=/app/app-gan.log
